// Generated by CIRCT firtool-1.62.0
module AdditionBasedOnlineNeuronComputation(	// src/main/scala/neuron/top_online_addition.scala:12:7
  input        clock,	// src/main/scala/neuron/top_online_addition.scala:12:7
               reset,	// src/main/scala/neuron/top_online_addition.scala:12:7
               io_start,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_0,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_1,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_2,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_3,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_4,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_5,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_6,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_7,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_8,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_9,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_10,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_11,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_12,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_13,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_14,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_15,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_16,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_17,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_18,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_19,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_20,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_21,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_22,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_23,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_24,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_25,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_26,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_27,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_28,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_29,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_30,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_31,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_32,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_33,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_34,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_35,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_36,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_37,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_38,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_39,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_40,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_41,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_42,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_43,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_44,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_45,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_46,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_47,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_48,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_49,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_50,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_51,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_52,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_53,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_54,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_55,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_56,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_57,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_58,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_59,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_60,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_61,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_62,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_63,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_64,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_65,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_66,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_67,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_68,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_69,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_70,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_71,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_72,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_73,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_74,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_75,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_76,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_77,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_78,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_79,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_80,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_81,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_82,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_83,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_84,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_85,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_86,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_87,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_88,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_89,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_90,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_91,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_92,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_93,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_94,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_95,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_96,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_97,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_98,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_99,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_100,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_101,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_102,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_103,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_104,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_105,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_106,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_107,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_108,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_109,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_110,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_111,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_112,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_113,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_114,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_115,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_116,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_117,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_118,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_119,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_120,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_121,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_122,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_123,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_124,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_125,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_126,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xp_127,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_0,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_1,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_2,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_3,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_4,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_5,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_6,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_7,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_8,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_9,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_10,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_11,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_12,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_13,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_14,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_15,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_16,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_17,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_18,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_19,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_20,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_21,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_22,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_23,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_24,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_25,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_26,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_27,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_28,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_29,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_30,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_31,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_32,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_33,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_34,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_35,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_36,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_37,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_38,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_39,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_40,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_41,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_42,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_43,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_44,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_45,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_46,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_47,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_48,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_49,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_50,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_51,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_52,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_53,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_54,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_55,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_56,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_57,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_58,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_59,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_60,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_61,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_62,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_63,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_64,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_65,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_66,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_67,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_68,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_69,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_70,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_71,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_72,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_73,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_74,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_75,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_76,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_77,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_78,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_79,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_80,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_81,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_82,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_83,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_84,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_85,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_86,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_87,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_88,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_89,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_90,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_91,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_92,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_93,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_94,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_95,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_96,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_97,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_98,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_99,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_100,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_101,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_102,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_103,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_104,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_105,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_106,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_107,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_108,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_109,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_110,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_111,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_112,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_113,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_114,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_115,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_116,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_117,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_118,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_119,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_120,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_121,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_122,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_123,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_124,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_125,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_126,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_xn_127,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_0,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_1,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_2,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_3,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_4,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_5,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_6,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_7,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_8,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_9,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_10,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_11,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_12,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_13,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_14,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_15,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_16,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_17,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_18,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_19,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_20,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_21,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_22,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_23,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_24,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_25,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_26,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_27,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_28,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_29,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_30,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_31,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_32,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_33,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_34,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_35,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_36,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_37,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_38,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_39,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_40,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_41,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_42,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_43,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_44,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_45,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_46,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_47,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_48,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_49,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_50,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_51,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_52,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_53,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_54,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_55,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_56,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_57,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_58,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_59,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_60,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_61,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_62,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_63,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_64,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_65,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_66,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_67,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_68,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_69,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_70,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_71,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_72,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_73,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_74,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_75,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_76,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_77,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_78,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_79,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_80,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_81,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_82,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_83,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_84,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_85,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_86,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_87,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_88,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_89,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_90,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_91,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_92,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_93,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_94,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_95,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_96,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_97,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_98,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_99,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_100,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_101,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_102,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_103,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_104,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_105,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_106,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_107,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_108,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_109,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_110,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_111,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_112,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_113,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_114,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_115,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_116,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_117,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_118,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_119,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_120,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_121,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_122,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_123,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_124,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_125,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_126,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yp_127,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_0,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_1,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_2,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_3,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_4,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_5,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_6,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_7,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_8,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_9,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_10,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_11,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_12,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_13,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_14,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_15,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_16,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_17,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_18,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_19,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_20,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_21,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_22,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_23,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_24,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_25,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_26,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_27,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_28,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_29,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_30,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_31,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_32,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_33,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_34,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_35,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_36,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_37,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_38,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_39,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_40,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_41,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_42,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_43,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_44,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_45,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_46,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_47,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_48,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_49,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_50,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_51,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_52,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_53,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_54,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_55,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_56,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_57,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_58,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_59,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_60,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_61,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_62,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_63,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_64,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_65,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_66,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_67,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_68,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_69,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_70,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_71,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_72,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_73,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_74,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_75,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_76,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_77,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_78,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_79,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_80,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_81,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_82,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_83,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_84,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_85,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_86,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_87,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_88,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_89,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_90,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_91,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_92,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_93,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_94,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_95,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_96,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_97,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_98,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_99,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_100,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_101,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_102,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_103,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_104,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_105,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_106,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_107,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_108,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_109,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_110,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_111,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_112,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_113,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_114,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_115,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_116,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_117,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_118,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_119,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_120,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_121,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_122,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_123,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_124,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_125,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_126,	// src/main/scala/neuron/top_online_addition.scala:16:14
               io_inputs_yn_127,	// src/main/scala/neuron/top_online_addition.scala:16:14
  output [1:0] io_result,	// src/main/scala/neuron/top_online_addition.scala:16:14
  output       io_resultValid	// src/main/scala/neuron/top_online_addition.scala:16:14
);

  wire [1:0] _onlineMultipleMultiplicationAdditionModule_io_result;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60
  wire       _onlineMultipleMultiplicationAdditionModule_io_resultValid;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60
  reg        firstDigit;	// src/main/scala/neuron/top_online_addition.scala:36:27
  reg        returnZero;	// src/main/scala/neuron/top_online_addition.scala:37:27
  reg  [1:0] delayedResult;	// src/main/scala/neuron/top_online_addition.scala:54:30
  reg        delayedResultValid;	// src/main/scala/neuron/top_online_addition.scala:55:35
  always @(posedge clock) begin	// src/main/scala/neuron/top_online_addition.scala:12:7
    if (reset) begin	// src/main/scala/neuron/top_online_addition.scala:12:7
      firstDigit <= 1'h0;	// src/main/scala/neuron/top_online_addition.scala:36:27
      returnZero <= 1'h0;	// src/main/scala/neuron/top_online_addition.scala:36:27, :37:27
    end
    else begin	// src/main/scala/neuron/top_online_addition.scala:12:7
      automatic logic _GEN =
        _onlineMultipleMultiplicationAdditionModule_io_resultValid & ~firstDigit;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60, src/main/scala/neuron/top_online_addition.scala:36:27, :63:{34,48}
      firstDigit <= _GEN | firstDigit;	// src/main/scala/neuron/top_online_addition.scala:36:27, :63:{34,61}, :65:16
      if (_GEN)	// src/main/scala/neuron/top_online_addition.scala:63:34
        returnZero <=
          _onlineMultipleMultiplicationAdditionModule_io_result[1] == _onlineMultipleMultiplicationAdditionModule_io_result[0]
          | _onlineMultipleMultiplicationAdditionModule_io_result[1];	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60, src/main/scala/neuron/top_online_addition.scala:37:27, :57:31, :58:31, :67:{23,40}
    end
    delayedResult <= _onlineMultipleMultiplicationAdditionModule_io_result;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60, src/main/scala/neuron/top_online_addition.scala:54:30
    delayedResultValid <= _onlineMultipleMultiplicationAdditionModule_io_resultValid;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60, src/main/scala/neuron/top_online_addition.scala:55:35
  end // always @(posedge)
  OnlineMultipleMultiplicationAddition onlineMultipleMultiplicationAdditionModule (	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:190:60
    .clock            (clock),
    .reset            (reset),
    .io_start         (io_start),
    .io_inputs_xp_0   (io_inputs_xp_0),
    .io_inputs_xp_2   (io_inputs_xp_2),
    .io_inputs_xp_4   (io_inputs_xp_4),
    .io_inputs_xp_6   (io_inputs_xp_6),
    .io_inputs_xp_8   (io_inputs_xp_8),
    .io_inputs_xp_10  (io_inputs_xp_10),
    .io_inputs_xp_12  (io_inputs_xp_12),
    .io_inputs_xp_14  (io_inputs_xp_14),
    .io_inputs_xp_16  (io_inputs_xp_16),
    .io_inputs_xp_18  (io_inputs_xp_18),
    .io_inputs_xp_20  (io_inputs_xp_20),
    .io_inputs_xp_22  (io_inputs_xp_22),
    .io_inputs_xp_24  (io_inputs_xp_24),
    .io_inputs_xp_26  (io_inputs_xp_26),
    .io_inputs_xp_28  (io_inputs_xp_28),
    .io_inputs_xp_30  (io_inputs_xp_30),
    .io_inputs_xp_32  (io_inputs_xp_32),
    .io_inputs_xp_34  (io_inputs_xp_34),
    .io_inputs_xp_36  (io_inputs_xp_36),
    .io_inputs_xp_38  (io_inputs_xp_38),
    .io_inputs_xp_40  (io_inputs_xp_40),
    .io_inputs_xp_42  (io_inputs_xp_42),
    .io_inputs_xp_44  (io_inputs_xp_44),
    .io_inputs_xp_46  (io_inputs_xp_46),
    .io_inputs_xp_48  (io_inputs_xp_48),
    .io_inputs_xp_50  (io_inputs_xp_50),
    .io_inputs_xp_52  (io_inputs_xp_52),
    .io_inputs_xp_54  (io_inputs_xp_54),
    .io_inputs_xp_56  (io_inputs_xp_56),
    .io_inputs_xp_58  (io_inputs_xp_58),
    .io_inputs_xp_60  (io_inputs_xp_60),
    .io_inputs_xp_62  (io_inputs_xp_62),
    .io_inputs_xp_64  (io_inputs_xp_64),
    .io_inputs_xp_66  (io_inputs_xp_66),
    .io_inputs_xp_68  (io_inputs_xp_68),
    .io_inputs_xp_70  (io_inputs_xp_70),
    .io_inputs_xp_72  (io_inputs_xp_72),
    .io_inputs_xp_74  (io_inputs_xp_74),
    .io_inputs_xp_76  (io_inputs_xp_76),
    .io_inputs_xp_78  (io_inputs_xp_78),
    .io_inputs_xp_80  (io_inputs_xp_80),
    .io_inputs_xp_82  (io_inputs_xp_82),
    .io_inputs_xp_84  (io_inputs_xp_84),
    .io_inputs_xp_86  (io_inputs_xp_86),
    .io_inputs_xp_88  (io_inputs_xp_88),
    .io_inputs_xp_90  (io_inputs_xp_90),
    .io_inputs_xp_92  (io_inputs_xp_92),
    .io_inputs_xp_94  (io_inputs_xp_94),
    .io_inputs_xp_96  (io_inputs_xp_96),
    .io_inputs_xp_98  (io_inputs_xp_98),
    .io_inputs_xp_100 (io_inputs_xp_100),
    .io_inputs_xp_102 (io_inputs_xp_102),
    .io_inputs_xp_104 (io_inputs_xp_104),
    .io_inputs_xp_106 (io_inputs_xp_106),
    .io_inputs_xp_108 (io_inputs_xp_108),
    .io_inputs_xp_110 (io_inputs_xp_110),
    .io_inputs_xp_112 (io_inputs_xp_112),
    .io_inputs_xp_114 (io_inputs_xp_114),
    .io_inputs_xp_116 (io_inputs_xp_116),
    .io_inputs_xp_118 (io_inputs_xp_118),
    .io_inputs_xp_120 (io_inputs_xp_120),
    .io_inputs_xp_122 (io_inputs_xp_122),
    .io_inputs_xp_124 (io_inputs_xp_124),
    .io_inputs_xp_126 (io_inputs_xp_126),
    .io_inputs_xn_1   (io_inputs_xn_1),
    .io_inputs_xn_3   (io_inputs_xn_3),
    .io_inputs_xn_5   (io_inputs_xn_5),
    .io_inputs_xn_7   (io_inputs_xn_7),
    .io_inputs_xn_9   (io_inputs_xn_9),
    .io_inputs_xn_11  (io_inputs_xn_11),
    .io_inputs_xn_13  (io_inputs_xn_13),
    .io_inputs_xn_15  (io_inputs_xn_15),
    .io_inputs_xn_17  (io_inputs_xn_17),
    .io_inputs_xn_19  (io_inputs_xn_19),
    .io_inputs_xn_21  (io_inputs_xn_21),
    .io_inputs_xn_23  (io_inputs_xn_23),
    .io_inputs_xn_25  (io_inputs_xn_25),
    .io_inputs_xn_27  (io_inputs_xn_27),
    .io_inputs_xn_29  (io_inputs_xn_29),
    .io_inputs_xn_31  (io_inputs_xn_31),
    .io_inputs_xn_33  (io_inputs_xn_33),
    .io_inputs_xn_35  (io_inputs_xn_35),
    .io_inputs_xn_37  (io_inputs_xn_37),
    .io_inputs_xn_39  (io_inputs_xn_39),
    .io_inputs_xn_41  (io_inputs_xn_41),
    .io_inputs_xn_43  (io_inputs_xn_43),
    .io_inputs_xn_45  (io_inputs_xn_45),
    .io_inputs_xn_47  (io_inputs_xn_47),
    .io_inputs_xn_49  (io_inputs_xn_49),
    .io_inputs_xn_51  (io_inputs_xn_51),
    .io_inputs_xn_53  (io_inputs_xn_53),
    .io_inputs_xn_55  (io_inputs_xn_55),
    .io_inputs_xn_57  (io_inputs_xn_57),
    .io_inputs_xn_59  (io_inputs_xn_59),
    .io_inputs_xn_61  (io_inputs_xn_61),
    .io_inputs_xn_63  (io_inputs_xn_63),
    .io_inputs_xn_65  (io_inputs_xn_65),
    .io_inputs_xn_67  (io_inputs_xn_67),
    .io_inputs_xn_69  (io_inputs_xn_69),
    .io_inputs_xn_71  (io_inputs_xn_71),
    .io_inputs_xn_73  (io_inputs_xn_73),
    .io_inputs_xn_75  (io_inputs_xn_75),
    .io_inputs_xn_77  (io_inputs_xn_77),
    .io_inputs_xn_79  (io_inputs_xn_79),
    .io_inputs_xn_81  (io_inputs_xn_81),
    .io_inputs_xn_83  (io_inputs_xn_83),
    .io_inputs_xn_85  (io_inputs_xn_85),
    .io_inputs_xn_87  (io_inputs_xn_87),
    .io_inputs_xn_89  (io_inputs_xn_89),
    .io_inputs_xn_91  (io_inputs_xn_91),
    .io_inputs_xn_93  (io_inputs_xn_93),
    .io_inputs_xn_95  (io_inputs_xn_95),
    .io_inputs_xn_97  (io_inputs_xn_97),
    .io_inputs_xn_99  (io_inputs_xn_99),
    .io_inputs_xn_101 (io_inputs_xn_101),
    .io_inputs_xn_103 (io_inputs_xn_103),
    .io_inputs_xn_105 (io_inputs_xn_105),
    .io_inputs_xn_107 (io_inputs_xn_107),
    .io_inputs_xn_109 (io_inputs_xn_109),
    .io_inputs_xn_111 (io_inputs_xn_111),
    .io_inputs_xn_113 (io_inputs_xn_113),
    .io_inputs_xn_115 (io_inputs_xn_115),
    .io_inputs_xn_117 (io_inputs_xn_117),
    .io_inputs_xn_119 (io_inputs_xn_119),
    .io_inputs_xn_121 (io_inputs_xn_121),
    .io_inputs_xn_123 (io_inputs_xn_123),
    .io_inputs_xn_125 (io_inputs_xn_125),
    .io_inputs_xn_127 (io_inputs_xn_127),
    .io_inputs_yp_0   (io_inputs_yp_0),
    .io_inputs_yp_2   (io_inputs_yp_2),
    .io_inputs_yp_4   (io_inputs_yp_4),
    .io_inputs_yp_6   (io_inputs_yp_6),
    .io_inputs_yp_8   (io_inputs_yp_8),
    .io_inputs_yp_10  (io_inputs_yp_10),
    .io_inputs_yp_12  (io_inputs_yp_12),
    .io_inputs_yp_14  (io_inputs_yp_14),
    .io_inputs_yp_16  (io_inputs_yp_16),
    .io_inputs_yp_18  (io_inputs_yp_18),
    .io_inputs_yp_20  (io_inputs_yp_20),
    .io_inputs_yp_22  (io_inputs_yp_22),
    .io_inputs_yp_24  (io_inputs_yp_24),
    .io_inputs_yp_26  (io_inputs_yp_26),
    .io_inputs_yp_28  (io_inputs_yp_28),
    .io_inputs_yp_30  (io_inputs_yp_30),
    .io_inputs_yp_32  (io_inputs_yp_32),
    .io_inputs_yp_34  (io_inputs_yp_34),
    .io_inputs_yp_36  (io_inputs_yp_36),
    .io_inputs_yp_38  (io_inputs_yp_38),
    .io_inputs_yp_40  (io_inputs_yp_40),
    .io_inputs_yp_42  (io_inputs_yp_42),
    .io_inputs_yp_44  (io_inputs_yp_44),
    .io_inputs_yp_46  (io_inputs_yp_46),
    .io_inputs_yp_48  (io_inputs_yp_48),
    .io_inputs_yp_50  (io_inputs_yp_50),
    .io_inputs_yp_52  (io_inputs_yp_52),
    .io_inputs_yp_54  (io_inputs_yp_54),
    .io_inputs_yp_56  (io_inputs_yp_56),
    .io_inputs_yp_58  (io_inputs_yp_58),
    .io_inputs_yp_60  (io_inputs_yp_60),
    .io_inputs_yp_62  (io_inputs_yp_62),
    .io_inputs_yp_64  (io_inputs_yp_64),
    .io_inputs_yp_66  (io_inputs_yp_66),
    .io_inputs_yp_68  (io_inputs_yp_68),
    .io_inputs_yp_70  (io_inputs_yp_70),
    .io_inputs_yp_72  (io_inputs_yp_72),
    .io_inputs_yp_74  (io_inputs_yp_74),
    .io_inputs_yp_76  (io_inputs_yp_76),
    .io_inputs_yp_78  (io_inputs_yp_78),
    .io_inputs_yp_80  (io_inputs_yp_80),
    .io_inputs_yp_82  (io_inputs_yp_82),
    .io_inputs_yp_84  (io_inputs_yp_84),
    .io_inputs_yp_86  (io_inputs_yp_86),
    .io_inputs_yp_88  (io_inputs_yp_88),
    .io_inputs_yp_90  (io_inputs_yp_90),
    .io_inputs_yp_92  (io_inputs_yp_92),
    .io_inputs_yp_94  (io_inputs_yp_94),
    .io_inputs_yp_96  (io_inputs_yp_96),
    .io_inputs_yp_98  (io_inputs_yp_98),
    .io_inputs_yp_100 (io_inputs_yp_100),
    .io_inputs_yp_102 (io_inputs_yp_102),
    .io_inputs_yp_104 (io_inputs_yp_104),
    .io_inputs_yp_106 (io_inputs_yp_106),
    .io_inputs_yp_108 (io_inputs_yp_108),
    .io_inputs_yp_110 (io_inputs_yp_110),
    .io_inputs_yp_112 (io_inputs_yp_112),
    .io_inputs_yp_114 (io_inputs_yp_114),
    .io_inputs_yp_116 (io_inputs_yp_116),
    .io_inputs_yp_118 (io_inputs_yp_118),
    .io_inputs_yp_120 (io_inputs_yp_120),
    .io_inputs_yp_122 (io_inputs_yp_122),
    .io_inputs_yp_124 (io_inputs_yp_124),
    .io_inputs_yp_126 (io_inputs_yp_126),
    .io_inputs_yn_1   (io_inputs_yn_1),
    .io_inputs_yn_3   (io_inputs_yn_3),
    .io_inputs_yn_5   (io_inputs_yn_5),
    .io_inputs_yn_7   (io_inputs_yn_7),
    .io_inputs_yn_9   (io_inputs_yn_9),
    .io_inputs_yn_11  (io_inputs_yn_11),
    .io_inputs_yn_13  (io_inputs_yn_13),
    .io_inputs_yn_15  (io_inputs_yn_15),
    .io_inputs_yn_17  (io_inputs_yn_17),
    .io_inputs_yn_19  (io_inputs_yn_19),
    .io_inputs_yn_21  (io_inputs_yn_21),
    .io_inputs_yn_23  (io_inputs_yn_23),
    .io_inputs_yn_25  (io_inputs_yn_25),
    .io_inputs_yn_27  (io_inputs_yn_27),
    .io_inputs_yn_29  (io_inputs_yn_29),
    .io_inputs_yn_31  (io_inputs_yn_31),
    .io_inputs_yn_33  (io_inputs_yn_33),
    .io_inputs_yn_35  (io_inputs_yn_35),
    .io_inputs_yn_37  (io_inputs_yn_37),
    .io_inputs_yn_39  (io_inputs_yn_39),
    .io_inputs_yn_41  (io_inputs_yn_41),
    .io_inputs_yn_43  (io_inputs_yn_43),
    .io_inputs_yn_45  (io_inputs_yn_45),
    .io_inputs_yn_47  (io_inputs_yn_47),
    .io_inputs_yn_49  (io_inputs_yn_49),
    .io_inputs_yn_51  (io_inputs_yn_51),
    .io_inputs_yn_53  (io_inputs_yn_53),
    .io_inputs_yn_55  (io_inputs_yn_55),
    .io_inputs_yn_57  (io_inputs_yn_57),
    .io_inputs_yn_59  (io_inputs_yn_59),
    .io_inputs_yn_61  (io_inputs_yn_61),
    .io_inputs_yn_63  (io_inputs_yn_63),
    .io_inputs_yn_65  (io_inputs_yn_65),
    .io_inputs_yn_67  (io_inputs_yn_67),
    .io_inputs_yn_69  (io_inputs_yn_69),
    .io_inputs_yn_71  (io_inputs_yn_71),
    .io_inputs_yn_73  (io_inputs_yn_73),
    .io_inputs_yn_75  (io_inputs_yn_75),
    .io_inputs_yn_77  (io_inputs_yn_77),
    .io_inputs_yn_79  (io_inputs_yn_79),
    .io_inputs_yn_81  (io_inputs_yn_81),
    .io_inputs_yn_83  (io_inputs_yn_83),
    .io_inputs_yn_85  (io_inputs_yn_85),
    .io_inputs_yn_87  (io_inputs_yn_87),
    .io_inputs_yn_89  (io_inputs_yn_89),
    .io_inputs_yn_91  (io_inputs_yn_91),
    .io_inputs_yn_93  (io_inputs_yn_93),
    .io_inputs_yn_95  (io_inputs_yn_95),
    .io_inputs_yn_97  (io_inputs_yn_97),
    .io_inputs_yn_99  (io_inputs_yn_99),
    .io_inputs_yn_101 (io_inputs_yn_101),
    .io_inputs_yn_103 (io_inputs_yn_103),
    .io_inputs_yn_105 (io_inputs_yn_105),
    .io_inputs_yn_107 (io_inputs_yn_107),
    .io_inputs_yn_109 (io_inputs_yn_109),
    .io_inputs_yn_111 (io_inputs_yn_111),
    .io_inputs_yn_113 (io_inputs_yn_113),
    .io_inputs_yn_115 (io_inputs_yn_115),
    .io_inputs_yn_117 (io_inputs_yn_117),
    .io_inputs_yn_119 (io_inputs_yn_119),
    .io_inputs_yn_121 (io_inputs_yn_121),
    .io_inputs_yn_123 (io_inputs_yn_123),
    .io_inputs_yn_125 (io_inputs_yn_125),
    .io_inputs_yn_127 (io_inputs_yn_127),
    .io_result        (_onlineMultipleMultiplicationAdditionModule_io_result),
    .io_resultValid   (_onlineMultipleMultiplicationAdditionModule_io_resultValid)
  );
  assign io_result = returnZero ? 2'h0 : delayedResult;	// src/main/scala/neuron/top_online_addition.scala:12:7, :37:27, :54:30, :83:31, :84:15, :86:15
  assign io_resultValid = delayedResultValid;	// src/main/scala/neuron/top_online_addition.scala:12:7, :55:35
endmodule

