// Generated by CIRCT firtool-1.62.0
module OLSDA(	// src/main/scala/neuron/components/online_adder.scala:24:7
  input        clock,	// src/main/scala/neuron/components/online_adder.scala:24:7
               reset,	// src/main/scala/neuron/components/online_adder.scala:24:7
  input  [3:0] io_x,	// src/main/scala/neuron/components/online_adder.scala:28:14
  output [1:0] io_z	// src/main/scala/neuron/components/online_adder.scala:28:14
);

  wire _FA2_io_s;	// src/main/scala/neuron/components/online_adder.scala:36:19
  wire _FA2_io_c;	// src/main/scala/neuron/components/online_adder.scala:36:19
  wire _FA1_io_s;	// src/main/scala/neuron/components/online_adder.scala:35:19
  reg  R1;	// src/main/scala/neuron/components/online_adder.scala:38:19
  reg  R2;	// src/main/scala/neuron/components/online_adder.scala:39:19
  reg  R3;	// src/main/scala/neuron/components/online_adder.scala:40:19
  reg  R4;	// src/main/scala/neuron/components/online_adder.scala:41:19
  reg  R5;	// src/main/scala/neuron/components/online_adder.scala:42:19
  reg  R6;	// src/main/scala/neuron/components/online_adder.scala:43:19
  always @(posedge clock) begin	// src/main/scala/neuron/components/online_adder.scala:24:7
    if (reset) begin	// src/main/scala/neuron/components/online_adder.scala:24:7
      R1 <= 1'h0;	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19, :38:19
      R2 <= 1'h0;	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19, :39:19
      R3 <= 1'h0;	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19, :40:19
      R4 <= 1'h0;	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19, :41:19
      R5 <= 1'h0;	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19, :42:19
      R6 <= 1'h0;	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19, :43:19
    end
    else begin	// src/main/scala/neuron/components/online_adder.scala:24:7
      R1 <= _FA1_io_s;	// src/main/scala/neuron/components/online_adder.scala:35:19, :38:19
      R2 <= io_x[0];	// src/main/scala/neuron/components/online_adder.scala:39:19, :58:13
      R3 <= _FA2_io_s;	// src/main/scala/neuron/components/online_adder.scala:36:19, :40:19
      R4 <= _FA2_io_c;	// src/main/scala/neuron/components/online_adder.scala:36:19, :41:19
      R5 <= R3;	// src/main/scala/neuron/components/online_adder.scala:40:19, :42:19
      R6 <= R4;	// src/main/scala/neuron/components/online_adder.scala:41:19, :43:19
    end
  end // always @(posedge)
  FullAdder FA1 (	// src/main/scala/neuron/components/online_adder.scala:35:19
    .io_x (io_x[3]),	// src/main/scala/neuron/components/online_adder.scala:45:19
    .io_y (io_x[2]),	// src/main/scala/neuron/components/online_adder.scala:46:19
    .io_z (io_x[1]),	// src/main/scala/neuron/components/online_adder.scala:47:19
    .io_s (_FA1_io_s),
    .io_c (/* unused */)
  );
  FullAdder FA2 (	// src/main/scala/neuron/components/online_adder.scala:36:19
    .io_x (R1),	// src/main/scala/neuron/components/online_adder.scala:38:19
    .io_y (R2),	// src/main/scala/neuron/components/online_adder.scala:39:19
    .io_z (1'h0),	// src/main/scala/neuron/components/online_adder.scala:28:14, :36:19
    .io_s (_FA2_io_s),
    .io_c (_FA2_io_c)
  );
  assign io_z = {R6, R5};	// src/main/scala/neuron/components/online_adder.scala:24:7, :42:19, :43:19, :64:14
endmodule

