// Generated by CIRCT firtool-1.62.0
module MultiplicationAndDivision(	// src/main/scala/neuron/components/multiplication_and_division.scala:8:7
  input         io_start,	// src/main/scala/neuron/components/multiplication_and_division.scala:14:14
  input  [31:0] io_in1,	// src/main/scala/neuron/components/multiplication_and_division.scala:14:14
                io_in2,	// src/main/scala/neuron/components/multiplication_and_division.scala:14:14
  output [63:0] io_result	// src/main/scala/neuron/components/multiplication_and_division.scala:14:14
);

  assign io_result =
    io_start ? {{32{io_in1[31]}}, io_in1} * {{32{io_in2[31]}}, io_in2} : 64'h0;	// src/main/scala/neuron/components/multiplication_and_division.scala:8:7, :30:30, :32:29, :39:{20,30}
endmodule

