// Generated by CIRCT firtool-1.62.0
module MultipleMultiplicationAddition(	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7
  input         clock,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7
                reset,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7
                io_start,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
  input  [31:0] io_inputs_0,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_1,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_2,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_3,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_4,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_5,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_6,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_7,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_8,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_9,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_10,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_11,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_12,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_13,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_14,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_15,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_16,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_17,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_18,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_19,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_20,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_21,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_22,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_23,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_24,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_25,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_26,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_27,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_28,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_29,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_30,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_31,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_32,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_33,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_34,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_35,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_36,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_37,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_38,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_39,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_40,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_41,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_42,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_43,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_44,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_45,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_46,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_47,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_48,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_49,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_50,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_51,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_52,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_53,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_54,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_55,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_56,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_57,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_58,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_59,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_60,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_61,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_62,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
                io_inputs_63,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
  output [69:0] io_result,	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
  output        io_resultValid	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
);

  wire [32:0]
    _regResultVec_62_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_61_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_60_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_59_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_58_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_57_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_56_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_55_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_54_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_53_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_52_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_51_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_50_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_49_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_48_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_47_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_46_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_45_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_44_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_43_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_42_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_41_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_40_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_39_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_38_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_37_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_36_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_35_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_34_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_33_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [32:0]
    _regResultVec_32_multiplicationAdditionionResult_additionAndSubtractionModule_io_result;	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
  wire [63:0]
    _regResultVec_31_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_30_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_29_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_28_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_27_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_26_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_25_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_24_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_23_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_22_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_21_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_20_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_19_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_18_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_17_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_16_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_15_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_14_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_13_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_12_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_11_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_10_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_9_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_8_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_7_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_6_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_5_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_4_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_3_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_2_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_1_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  wire [63:0]
    _regResultVec_0_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result;	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
  reg  [5:0]  delayCount;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:107:27
  reg  [69:0] regResultVec_0_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_1_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_2_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_3_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_4_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_5_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_6_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_7_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_8_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_9_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_10_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_11_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_12_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_13_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_14_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_15_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_16_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_17_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_18_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_19_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_20_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_21_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_22_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_23_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_24_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_25_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_26_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_27_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_28_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_29_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_30_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_31_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_32_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_33_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_34_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_35_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_36_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_37_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_38_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_39_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_40_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_41_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_42_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_43_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_44_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_45_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_46_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_47_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_48_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_49_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_50_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_51_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_52_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_53_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_54_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_55_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_56_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_57_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_58_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_59_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_60_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_61_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  reg  [69:0] regResultVec_62_multiplicationAdditionionResult;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
  wire        _GEN = delayCount == 6'h6;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:107:27, :131:21
  always @(posedge clock) begin	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7
    if (reset)	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7
      delayCount <= 6'h0;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:107:27
    else if (io_start) begin	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
      if (~_GEN)	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:131:21
        delayCount <= delayCount + 6'h1;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:107:27, :134:32
    end
    else	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
      delayCount <= 6'h0;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:107:27
    if (io_start) begin	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:87:14
      regResultVec_0_multiplicationAdditionionResult <=
        {{6{_regResultVec_0_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_0_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_1_multiplicationAdditionionResult <=
        {{6{_regResultVec_1_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_1_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_2_multiplicationAdditionionResult <=
        {{6{_regResultVec_2_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_2_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_3_multiplicationAdditionionResult <=
        {{6{_regResultVec_3_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_3_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_4_multiplicationAdditionionResult <=
        {{6{_regResultVec_4_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_4_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_5_multiplicationAdditionionResult <=
        {{6{_regResultVec_5_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_5_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_6_multiplicationAdditionionResult <=
        {{6{_regResultVec_6_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_6_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_7_multiplicationAdditionionResult <=
        {{6{_regResultVec_7_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_7_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_8_multiplicationAdditionionResult <=
        {{6{_regResultVec_8_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_8_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_9_multiplicationAdditionionResult <=
        {{6{_regResultVec_9_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_9_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_10_multiplicationAdditionionResult <=
        {{6{_regResultVec_10_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_10_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_11_multiplicationAdditionionResult <=
        {{6{_regResultVec_11_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_11_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_12_multiplicationAdditionionResult <=
        {{6{_regResultVec_12_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_12_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_13_multiplicationAdditionionResult <=
        {{6{_regResultVec_13_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_13_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_14_multiplicationAdditionionResult <=
        {{6{_regResultVec_14_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_14_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_15_multiplicationAdditionionResult <=
        {{6{_regResultVec_15_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_15_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_16_multiplicationAdditionionResult <=
        {{6{_regResultVec_16_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_16_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_17_multiplicationAdditionionResult <=
        {{6{_regResultVec_17_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_17_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_18_multiplicationAdditionionResult <=
        {{6{_regResultVec_18_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_18_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_19_multiplicationAdditionionResult <=
        {{6{_regResultVec_19_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_19_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_20_multiplicationAdditionionResult <=
        {{6{_regResultVec_20_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_20_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_21_multiplicationAdditionionResult <=
        {{6{_regResultVec_21_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_21_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_22_multiplicationAdditionionResult <=
        {{6{_regResultVec_22_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_22_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_23_multiplicationAdditionionResult <=
        {{6{_regResultVec_23_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_23_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_24_multiplicationAdditionionResult <=
        {{6{_regResultVec_24_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_24_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_25_multiplicationAdditionionResult <=
        {{6{_regResultVec_25_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_25_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_26_multiplicationAdditionionResult <=
        {{6{_regResultVec_26_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_26_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_27_multiplicationAdditionionResult <=
        {{6{_regResultVec_27_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_27_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_28_multiplicationAdditionionResult <=
        {{6{_regResultVec_28_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_28_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_29_multiplicationAdditionionResult <=
        {{6{_regResultVec_29_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_29_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_30_multiplicationAdditionionResult <=
        {{6{_regResultVec_30_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_30_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_31_multiplicationAdditionionResult <=
        {{6{_regResultVec_31_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result[63]}},
         _regResultVec_31_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result};	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :158:57, src/main/scala/neuron/components/multiplication_and_division.scala:70:49
      regResultVec_32_multiplicationAdditionionResult <=
        {{37{_regResultVec_32_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_32_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_33_multiplicationAdditionionResult <=
        {{37{_regResultVec_33_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_33_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_34_multiplicationAdditionionResult <=
        {{37{_regResultVec_34_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_34_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_35_multiplicationAdditionionResult <=
        {{37{_regResultVec_35_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_35_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_36_multiplicationAdditionionResult <=
        {{37{_regResultVec_36_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_36_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_37_multiplicationAdditionionResult <=
        {{37{_regResultVec_37_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_37_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_38_multiplicationAdditionionResult <=
        {{37{_regResultVec_38_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_38_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_39_multiplicationAdditionionResult <=
        {{37{_regResultVec_39_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_39_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_40_multiplicationAdditionionResult <=
        {{37{_regResultVec_40_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_40_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_41_multiplicationAdditionionResult <=
        {{37{_regResultVec_41_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_41_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_42_multiplicationAdditionionResult <=
        {{37{_regResultVec_42_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_42_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_43_multiplicationAdditionionResult <=
        {{37{_regResultVec_43_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_43_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_44_multiplicationAdditionionResult <=
        {{37{_regResultVec_44_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_44_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_45_multiplicationAdditionionResult <=
        {{37{_regResultVec_45_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_45_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_46_multiplicationAdditionionResult <=
        {{37{_regResultVec_46_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_46_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_47_multiplicationAdditionionResult <=
        {{37{_regResultVec_47_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_47_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_48_multiplicationAdditionionResult <=
        {{37{_regResultVec_48_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_48_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_49_multiplicationAdditionionResult <=
        {{37{_regResultVec_49_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_49_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_50_multiplicationAdditionionResult <=
        {{37{_regResultVec_50_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_50_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_51_multiplicationAdditionionResult <=
        {{37{_regResultVec_51_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_51_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_52_multiplicationAdditionionResult <=
        {{37{_regResultVec_52_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_52_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_53_multiplicationAdditionionResult <=
        {{37{_regResultVec_53_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_53_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_54_multiplicationAdditionionResult <=
        {{37{_regResultVec_54_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_54_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_55_multiplicationAdditionionResult <=
        {{37{_regResultVec_55_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_55_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_56_multiplicationAdditionionResult <=
        {{37{_regResultVec_56_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_56_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_57_multiplicationAdditionionResult <=
        {{37{_regResultVec_57_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_57_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_58_multiplicationAdditionionResult <=
        {{37{_regResultVec_58_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_58_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_59_multiplicationAdditionionResult <=
        {{37{_regResultVec_59_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_59_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_60_multiplicationAdditionionResult <=
        {{37{_regResultVec_60_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_60_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_61_multiplicationAdditionionResult <=
        {{37{_regResultVec_61_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_61_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
      regResultVec_62_multiplicationAdditionionResult <=
        {{37{_regResultVec_62_multiplicationAdditionionResult_additionAndSubtractionModule_io_result[32]}},
         _regResultVec_62_multiplicationAdditionionResult_additionAndSubtractionModule_io_result};	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25, :199:59
    end
  end // always @(posedge)
  MultiplicationAndDivision regResultVec_0_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_0),
    .io_in2    (io_inputs_1),
    .io_result
      (_regResultVec_0_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_1_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_2),
    .io_in2    (io_inputs_3),
    .io_result
      (_regResultVec_1_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_2_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_4),
    .io_in2    (io_inputs_5),
    .io_result
      (_regResultVec_2_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_3_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_6),
    .io_in2    (io_inputs_7),
    .io_result
      (_regResultVec_3_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_4_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_8),
    .io_in2    (io_inputs_9),
    .io_result
      (_regResultVec_4_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_5_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_10),
    .io_in2    (io_inputs_11),
    .io_result
      (_regResultVec_5_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_6_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_12),
    .io_in2    (io_inputs_13),
    .io_result
      (_regResultVec_6_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_7_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_14),
    .io_in2    (io_inputs_15),
    .io_result
      (_regResultVec_7_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_8_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_16),
    .io_in2    (io_inputs_17),
    .io_result
      (_regResultVec_8_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_9_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_18),
    .io_in2    (io_inputs_19),
    .io_result
      (_regResultVec_9_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_10_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_20),
    .io_in2    (io_inputs_21),
    .io_result
      (_regResultVec_10_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_11_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_22),
    .io_in2    (io_inputs_23),
    .io_result
      (_regResultVec_11_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_12_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_24),
    .io_in2    (io_inputs_25),
    .io_result
      (_regResultVec_12_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_13_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_26),
    .io_in2    (io_inputs_27),
    .io_result
      (_regResultVec_13_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_14_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_28),
    .io_in2    (io_inputs_29),
    .io_result
      (_regResultVec_14_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_15_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_30),
    .io_in2    (io_inputs_31),
    .io_result
      (_regResultVec_15_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_16_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_32),
    .io_in2    (io_inputs_33),
    .io_result
      (_regResultVec_16_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_17_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_34),
    .io_in2    (io_inputs_35),
    .io_result
      (_regResultVec_17_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_18_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_36),
    .io_in2    (io_inputs_37),
    .io_result
      (_regResultVec_18_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_19_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_38),
    .io_in2    (io_inputs_39),
    .io_result
      (_regResultVec_19_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_20_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_40),
    .io_in2    (io_inputs_41),
    .io_result
      (_regResultVec_20_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_21_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_42),
    .io_in2    (io_inputs_43),
    .io_result
      (_regResultVec_21_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_22_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_44),
    .io_in2    (io_inputs_45),
    .io_result
      (_regResultVec_22_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_23_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_46),
    .io_in2    (io_inputs_47),
    .io_result
      (_regResultVec_23_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_24_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_48),
    .io_in2    (io_inputs_49),
    .io_result
      (_regResultVec_24_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_25_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_50),
    .io_in2    (io_inputs_51),
    .io_result
      (_regResultVec_25_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_26_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_52),
    .io_in2    (io_inputs_53),
    .io_result
      (_regResultVec_26_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_27_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_54),
    .io_in2    (io_inputs_55),
    .io_result
      (_regResultVec_27_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_28_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_56),
    .io_in2    (io_inputs_57),
    .io_result
      (_regResultVec_28_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_29_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_58),
    .io_in2    (io_inputs_59),
    .io_result
      (_regResultVec_29_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_30_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_60),
    .io_in2    (io_inputs_61),
    .io_result
      (_regResultVec_30_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  MultiplicationAndDivision regResultVec_31_multiplicationAdditionionResult_multiplicationAndDivisionModule (	// src/main/scala/neuron/components/multiplication_and_division.scala:70:49
    .io_start  (io_start),
    .io_in1    (io_inputs_62),
    .io_in2    (io_inputs_63),
    .io_result
      (_regResultVec_31_multiplicationAdditionionResult_multiplicationAndDivisionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_32_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_0_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_1_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_32_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_33_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_2_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_3_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_33_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_34_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_4_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_5_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_34_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_35_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_6_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_7_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_35_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_36_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_8_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_9_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_36_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_37_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_10_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_11_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_37_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_38_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_12_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_13_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_38_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_39_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_14_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_15_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_39_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_40_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_16_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_17_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_40_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_41_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_18_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_19_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_41_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_42_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_20_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_21_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_42_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_43_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_22_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_23_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_43_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_44_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_24_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_25_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_44_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_45_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_26_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_27_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_45_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_46_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_28_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_29_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_46_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_47_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_30_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_31_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_47_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_48_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_32_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_33_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_48_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_49_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_34_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_35_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_49_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_50_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_36_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_37_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_50_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_51_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_38_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_39_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_51_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_52_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_40_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_41_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_52_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_53_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_42_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_43_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_53_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_54_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_44_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_45_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_54_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_55_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_46_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_47_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_55_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_56_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_48_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_49_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_56_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_57_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_50_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_51_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_57_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_58_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_52_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_53_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_58_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_59_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_54_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_55_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_59_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_60_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_56_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_57_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_60_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_61_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_58_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_59_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_61_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  AdditionAndSubtraction regResultVec_62_multiplicationAdditionionResult_additionAndSubtractionModule (	// src/main/scala/neuron/components/addition_and_subtraction.scala:70:46
    .io_start  (io_start),
    .io_in1    (regResultVec_60_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:79:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_in2    (regResultVec_61_multiplicationAdditionionResult[31:0]),	// src/main/scala/neuron/components/addition_and_subtraction.scala:80:41, src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:110:25
    .io_result
      (_regResultVec_62_multiplicationAdditionionResult_additionAndSubtractionModule_io_result)
  );
  assign io_result = io_start ? regResultVec_62_multiplicationAdditionionResult : 70'h0;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7, :110:25, :120:16, :126:18, :225:18
  assign io_resultValid = io_start & _GEN;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:71:7, :126:18, :131:{21,44}, :226:17
endmodule

