// Generated by CIRCT firtool-1.62.0
module AdditionAndSubtraction(	// src/main/scala/neuron/components/addition_and_subtraction.scala:8:7
  input         io_start,	// src/main/scala/neuron/components/addition_and_subtraction.scala:14:14
  input  [31:0] io_in1,	// src/main/scala/neuron/components/addition_and_subtraction.scala:14:14
                io_in2,	// src/main/scala/neuron/components/addition_and_subtraction.scala:14:14
  output [32:0] io_result	// src/main/scala/neuron/components/addition_and_subtraction.scala:14:14
);

  wire [31:0] _resultOutput_T = io_in1 + io_in2;	// src/main/scala/neuron/components/addition_and_subtraction.scala:39:30
  assign io_result = io_start ? {_resultOutput_T[31], _resultOutput_T} : 33'h0;	// src/main/scala/neuron/components/addition_and_subtraction.scala:8:7, :30:30, :32:29, :39:{20,30}
endmodule

