// Generated by CIRCT firtool-1.62.0
module FullAdder(	// src/main/scala/neuron/components/online_adder.scala:11:7
  input  io_x,	// src/main/scala/neuron/components/online_adder.scala:12:14
         io_y,	// src/main/scala/neuron/components/online_adder.scala:12:14
         io_z,	// src/main/scala/neuron/components/online_adder.scala:12:14
  output io_s,	// src/main/scala/neuron/components/online_adder.scala:12:14
         io_c	// src/main/scala/neuron/components/online_adder.scala:12:14
);

  assign io_s = io_x ^ io_y ^ io_z;	// src/main/scala/neuron/components/online_adder.scala:11:7, :20:23
  assign io_c = io_x & io_y | io_x & io_z | io_z & io_y;	// src/main/scala/neuron/components/online_adder.scala:11:7, :21:{17,33,41,49}
endmodule

