// Generated by CIRCT firtool-1.62.0
module AdditionBasedRegularNeuronComputation(	// src/main/scala/neuron/top_regular_addition.scala:12:7
  input         clock,	// src/main/scala/neuron/top_regular_addition.scala:12:7
                reset,	// src/main/scala/neuron/top_regular_addition.scala:12:7
                io_start,	// src/main/scala/neuron/top_regular_addition.scala:17:14
  input  [31:0] io_inputs_0,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_1,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_2,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_3,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_4,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_5,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_6,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_7,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_8,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_9,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_10,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_11,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_12,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_13,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_14,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_15,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_16,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_17,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_18,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_19,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_20,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_21,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_22,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_23,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_24,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_25,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_26,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_27,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_28,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_29,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_30,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_31,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_32,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_33,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_34,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_35,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_36,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_37,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_38,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_39,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_40,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_41,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_42,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_43,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_44,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_45,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_46,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_47,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_48,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_49,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_50,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_51,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_52,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_53,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_54,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_55,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_56,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_57,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_58,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_59,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_60,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_61,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_62,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_63,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_64,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_65,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_66,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_67,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_68,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_69,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_70,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_71,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_72,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_73,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_74,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_75,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_76,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_77,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_78,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_79,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_80,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_81,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_82,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_83,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_84,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_85,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_86,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_87,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_88,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_89,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_90,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_91,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_92,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_93,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_94,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_95,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_96,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_97,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_98,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_99,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_100,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_101,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_102,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_103,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_104,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_105,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_106,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_107,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_108,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_109,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_110,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_111,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_112,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_113,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_114,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_115,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_116,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_117,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_118,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_119,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_120,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_121,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_122,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_123,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_124,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_125,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_126,	// src/main/scala/neuron/top_regular_addition.scala:17:14
                io_inputs_127,	// src/main/scala/neuron/top_regular_addition.scala:17:14
  output [70:0] io_result,	// src/main/scala/neuron/top_regular_addition.scala:17:14
  output        io_resultValid	// src/main/scala/neuron/top_regular_addition.scala:17:14
);

  wire [70:0] _multipleMultiplicationAdditionModule_io_result;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:249:54
  MultipleMultiplicationAddition multipleMultiplicationAdditionModule (	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:249:54
    .clock          (clock),
    .reset          (reset),
    .io_start       (io_start),
    .io_inputs_0    (io_inputs_0),
    .io_inputs_1    (io_inputs_1),
    .io_inputs_2    (io_inputs_2),
    .io_inputs_3    (io_inputs_3),
    .io_inputs_4    (io_inputs_4),
    .io_inputs_5    (io_inputs_5),
    .io_inputs_6    (io_inputs_6),
    .io_inputs_7    (io_inputs_7),
    .io_inputs_8    (io_inputs_8),
    .io_inputs_9    (io_inputs_9),
    .io_inputs_10   (io_inputs_10),
    .io_inputs_11   (io_inputs_11),
    .io_inputs_12   (io_inputs_12),
    .io_inputs_13   (io_inputs_13),
    .io_inputs_14   (io_inputs_14),
    .io_inputs_15   (io_inputs_15),
    .io_inputs_16   (io_inputs_16),
    .io_inputs_17   (io_inputs_17),
    .io_inputs_18   (io_inputs_18),
    .io_inputs_19   (io_inputs_19),
    .io_inputs_20   (io_inputs_20),
    .io_inputs_21   (io_inputs_21),
    .io_inputs_22   (io_inputs_22),
    .io_inputs_23   (io_inputs_23),
    .io_inputs_24   (io_inputs_24),
    .io_inputs_25   (io_inputs_25),
    .io_inputs_26   (io_inputs_26),
    .io_inputs_27   (io_inputs_27),
    .io_inputs_28   (io_inputs_28),
    .io_inputs_29   (io_inputs_29),
    .io_inputs_30   (io_inputs_30),
    .io_inputs_31   (io_inputs_31),
    .io_inputs_32   (io_inputs_32),
    .io_inputs_33   (io_inputs_33),
    .io_inputs_34   (io_inputs_34),
    .io_inputs_35   (io_inputs_35),
    .io_inputs_36   (io_inputs_36),
    .io_inputs_37   (io_inputs_37),
    .io_inputs_38   (io_inputs_38),
    .io_inputs_39   (io_inputs_39),
    .io_inputs_40   (io_inputs_40),
    .io_inputs_41   (io_inputs_41),
    .io_inputs_42   (io_inputs_42),
    .io_inputs_43   (io_inputs_43),
    .io_inputs_44   (io_inputs_44),
    .io_inputs_45   (io_inputs_45),
    .io_inputs_46   (io_inputs_46),
    .io_inputs_47   (io_inputs_47),
    .io_inputs_48   (io_inputs_48),
    .io_inputs_49   (io_inputs_49),
    .io_inputs_50   (io_inputs_50),
    .io_inputs_51   (io_inputs_51),
    .io_inputs_52   (io_inputs_52),
    .io_inputs_53   (io_inputs_53),
    .io_inputs_54   (io_inputs_54),
    .io_inputs_55   (io_inputs_55),
    .io_inputs_56   (io_inputs_56),
    .io_inputs_57   (io_inputs_57),
    .io_inputs_58   (io_inputs_58),
    .io_inputs_59   (io_inputs_59),
    .io_inputs_60   (io_inputs_60),
    .io_inputs_61   (io_inputs_61),
    .io_inputs_62   (io_inputs_62),
    .io_inputs_63   (io_inputs_63),
    .io_inputs_64   (io_inputs_64),
    .io_inputs_65   (io_inputs_65),
    .io_inputs_66   (io_inputs_66),
    .io_inputs_67   (io_inputs_67),
    .io_inputs_68   (io_inputs_68),
    .io_inputs_69   (io_inputs_69),
    .io_inputs_70   (io_inputs_70),
    .io_inputs_71   (io_inputs_71),
    .io_inputs_72   (io_inputs_72),
    .io_inputs_73   (io_inputs_73),
    .io_inputs_74   (io_inputs_74),
    .io_inputs_75   (io_inputs_75),
    .io_inputs_76   (io_inputs_76),
    .io_inputs_77   (io_inputs_77),
    .io_inputs_78   (io_inputs_78),
    .io_inputs_79   (io_inputs_79),
    .io_inputs_80   (io_inputs_80),
    .io_inputs_81   (io_inputs_81),
    .io_inputs_82   (io_inputs_82),
    .io_inputs_83   (io_inputs_83),
    .io_inputs_84   (io_inputs_84),
    .io_inputs_85   (io_inputs_85),
    .io_inputs_86   (io_inputs_86),
    .io_inputs_87   (io_inputs_87),
    .io_inputs_88   (io_inputs_88),
    .io_inputs_89   (io_inputs_89),
    .io_inputs_90   (io_inputs_90),
    .io_inputs_91   (io_inputs_91),
    .io_inputs_92   (io_inputs_92),
    .io_inputs_93   (io_inputs_93),
    .io_inputs_94   (io_inputs_94),
    .io_inputs_95   (io_inputs_95),
    .io_inputs_96   (io_inputs_96),
    .io_inputs_97   (io_inputs_97),
    .io_inputs_98   (io_inputs_98),
    .io_inputs_99   (io_inputs_99),
    .io_inputs_100  (io_inputs_100),
    .io_inputs_101  (io_inputs_101),
    .io_inputs_102  (io_inputs_102),
    .io_inputs_103  (io_inputs_103),
    .io_inputs_104  (io_inputs_104),
    .io_inputs_105  (io_inputs_105),
    .io_inputs_106  (io_inputs_106),
    .io_inputs_107  (io_inputs_107),
    .io_inputs_108  (io_inputs_108),
    .io_inputs_109  (io_inputs_109),
    .io_inputs_110  (io_inputs_110),
    .io_inputs_111  (io_inputs_111),
    .io_inputs_112  (io_inputs_112),
    .io_inputs_113  (io_inputs_113),
    .io_inputs_114  (io_inputs_114),
    .io_inputs_115  (io_inputs_115),
    .io_inputs_116  (io_inputs_116),
    .io_inputs_117  (io_inputs_117),
    .io_inputs_118  (io_inputs_118),
    .io_inputs_119  (io_inputs_119),
    .io_inputs_120  (io_inputs_120),
    .io_inputs_121  (io_inputs_121),
    .io_inputs_122  (io_inputs_122),
    .io_inputs_123  (io_inputs_123),
    .io_inputs_124  (io_inputs_124),
    .io_inputs_125  (io_inputs_125),
    .io_inputs_126  (io_inputs_126),
    .io_inputs_127  (io_inputs_127),
    .io_result      (_multipleMultiplicationAdditionModule_io_result),
    .io_resultValid (io_resultValid)
  );
  assign io_result =
    $signed(_multipleMultiplicationAdditionModule_io_result) > -71'sh1
      ? _multipleMultiplicationAdditionModule_io_result
      : 71'h0;	// src/main/scala/neuron/components/multiple_multiplication_and_addition.scala:249:54, src/main/scala/neuron/top_regular_addition.scala:12:7, :53:{15,23}, :54:15, :56:15
endmodule

