// Generated by CIRCT firtool-1.62.0
module OnlineMultipleMultiplicationAddition(	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7
  input        clock,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7
               reset,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7
               io_start,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_0,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_2,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_4,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_6,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_8,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_10,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_12,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_14,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_16,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_18,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_20,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_22,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_24,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_26,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_28,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_30,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_32,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_34,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_36,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_38,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_40,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_42,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_44,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_46,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_48,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_50,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_52,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_54,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_56,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_58,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_60,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xp_62,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_1,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_3,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_5,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_7,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_9,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_11,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_13,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_15,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_17,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_19,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_21,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_23,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_25,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_27,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_29,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_31,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_33,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_35,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_37,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_39,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_41,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_43,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_45,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_47,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_49,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_51,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_53,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_55,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_57,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_59,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_61,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_xn_63,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_0,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_2,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_4,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_6,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_8,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_10,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_12,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_14,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_16,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_18,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_20,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_22,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_24,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_26,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_28,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_30,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_32,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_34,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_36,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_38,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_40,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_42,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_44,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_46,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_48,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_50,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_52,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_54,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_56,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_58,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_60,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yp_62,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_1,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_3,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_5,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_7,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_9,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_11,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_13,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_15,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_17,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_19,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_21,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_23,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_25,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_27,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_29,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_31,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_33,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_35,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_37,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_39,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_41,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_43,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_45,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_47,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_49,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_51,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_53,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_55,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_57,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_59,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_61,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
               io_inputs_yn_63,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
  output [1:0] io_result,	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
  output       io_resultValid	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
);

  wire [1:0] _oLSDAModule_30_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_29_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_28_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_27_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_26_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_25_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_24_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_23_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_22_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_21_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_20_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_19_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_18_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_17_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_16_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_15_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_14_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_13_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_12_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_11_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_10_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_9_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_8_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_7_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_6_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_5_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_4_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_3_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_2_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_1_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire [1:0] _oLSDAModule_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29
  wire       _rOO4_VerilogModule_31_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_31_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_30_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_30_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_29_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_29_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_28_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_28_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_27_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_27_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_26_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_26_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_25_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_25_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_24_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_24_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_23_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_23_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_22_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_22_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_21_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_21_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_20_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_20_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_19_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_19_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_18_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_18_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_17_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_17_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_16_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_16_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_15_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_15_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_14_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_14_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_13_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_13_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_12_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_12_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_11_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_11_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_10_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_10_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_9_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_9_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_8_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_8_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_7_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_7_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_6_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_6_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_5_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_5_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_4_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_4_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_3_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_3_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_2_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_2_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_1_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_1_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_io_zp;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  wire       _rOO4_VerilogModule_io_zn;	// src/main/scala/neuron/components/online_multiplier.scala:100:36
  reg  [5:0] delayCount;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:53:27
  reg  [1:0] regVecZ_0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_1;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_2;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_3;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_4;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_5;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_6;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_7;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_8;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_9;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_10;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_11;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_12;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_13;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_14;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_15;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_16;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_17;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_18;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_19;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_20;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_21;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_22;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_23;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_24;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_25;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_26;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_27;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_28;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_29;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_30;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_31;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_32;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_33;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_34;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_35;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_36;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_37;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_38;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_39;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_40;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_41;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_42;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_43;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_44;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_45;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_46;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_47;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_48;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_49;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_50;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_51;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_52;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_53;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_54;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_55;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_56;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_57;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_58;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_59;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_60;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_61;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  reg  [1:0] regVecZ_62;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
  wire       _GEN = delayCount == 6'h6;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:53:27, :81:21
  always @(posedge clock) begin	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7
    if (reset) begin	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7
      delayCount <= 6'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:53:27
      regVecZ_0 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_1 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_2 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_3 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_4 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_5 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_6 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_7 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_8 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_9 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_10 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_11 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_12 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_13 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_14 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_15 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_16 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_17 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_18 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_19 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_20 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_21 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_22 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_23 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_24 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_25 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_26 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_27 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_28 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_29 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_30 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_31 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_32 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_33 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_34 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_35 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_36 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_37 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_38 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_39 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_40 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_41 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_42 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_43 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_44 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_45 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_46 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_47 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_48 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_49 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_50 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_51 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_52 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_53 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_54 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_55 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_56 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_57 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_58 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_59 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_60 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_61 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
      regVecZ_62 <= 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :57:12
    end
    else if (io_start) begin	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
      if (~_GEN)	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:81:21
        delayCount <= delayCount + 6'h1;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:53:27, :85:34
      regVecZ_0 <= {_rOO4_VerilogModule_io_zp, _rOO4_VerilogModule_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_1 <= {_rOO4_VerilogModule_1_io_zp, _rOO4_VerilogModule_1_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_2 <= {_rOO4_VerilogModule_2_io_zp, _rOO4_VerilogModule_2_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_3 <= {_rOO4_VerilogModule_3_io_zp, _rOO4_VerilogModule_3_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_4 <= {_rOO4_VerilogModule_4_io_zp, _rOO4_VerilogModule_4_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_5 <= {_rOO4_VerilogModule_5_io_zp, _rOO4_VerilogModule_5_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_6 <= {_rOO4_VerilogModule_6_io_zp, _rOO4_VerilogModule_6_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_7 <= {_rOO4_VerilogModule_7_io_zp, _rOO4_VerilogModule_7_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_8 <= {_rOO4_VerilogModule_8_io_zp, _rOO4_VerilogModule_8_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_9 <= {_rOO4_VerilogModule_9_io_zp, _rOO4_VerilogModule_9_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_10 <= {_rOO4_VerilogModule_10_io_zp, _rOO4_VerilogModule_10_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_11 <= {_rOO4_VerilogModule_11_io_zp, _rOO4_VerilogModule_11_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_12 <= {_rOO4_VerilogModule_12_io_zp, _rOO4_VerilogModule_12_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_13 <= {_rOO4_VerilogModule_13_io_zp, _rOO4_VerilogModule_13_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_14 <= {_rOO4_VerilogModule_14_io_zp, _rOO4_VerilogModule_14_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_15 <= {_rOO4_VerilogModule_15_io_zp, _rOO4_VerilogModule_15_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_16 <= {_rOO4_VerilogModule_16_io_zp, _rOO4_VerilogModule_16_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_17 <= {_rOO4_VerilogModule_17_io_zp, _rOO4_VerilogModule_17_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_18 <= {_rOO4_VerilogModule_18_io_zp, _rOO4_VerilogModule_18_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_19 <= {_rOO4_VerilogModule_19_io_zp, _rOO4_VerilogModule_19_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_20 <= {_rOO4_VerilogModule_20_io_zp, _rOO4_VerilogModule_20_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_21 <= {_rOO4_VerilogModule_21_io_zp, _rOO4_VerilogModule_21_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_22 <= {_rOO4_VerilogModule_22_io_zp, _rOO4_VerilogModule_22_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_23 <= {_rOO4_VerilogModule_23_io_zp, _rOO4_VerilogModule_23_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_24 <= {_rOO4_VerilogModule_24_io_zp, _rOO4_VerilogModule_24_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_25 <= {_rOO4_VerilogModule_25_io_zp, _rOO4_VerilogModule_25_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_26 <= {_rOO4_VerilogModule_26_io_zp, _rOO4_VerilogModule_26_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_27 <= {_rOO4_VerilogModule_27_io_zp, _rOO4_VerilogModule_27_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_28 <= {_rOO4_VerilogModule_28_io_zp, _rOO4_VerilogModule_28_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_29 <= {_rOO4_VerilogModule_29_io_zp, _rOO4_VerilogModule_29_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_30 <= {_rOO4_VerilogModule_30_io_zp, _rOO4_VerilogModule_30_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_31 <= {_rOO4_VerilogModule_31_io_zp, _rOO4_VerilogModule_31_io_zn};	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :112:26, src/main/scala/neuron/components/online_multiplier.scala:100:36
      regVecZ_32 <= _oLSDAModule_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_33 <= _oLSDAModule_1_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_34 <= _oLSDAModule_2_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_35 <= _oLSDAModule_3_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_36 <= _oLSDAModule_4_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_37 <= _oLSDAModule_5_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_38 <= _oLSDAModule_6_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_39 <= _oLSDAModule_7_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_40 <= _oLSDAModule_8_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_41 <= _oLSDAModule_9_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_42 <= _oLSDAModule_10_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_43 <= _oLSDAModule_11_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_44 <= _oLSDAModule_12_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_45 <= _oLSDAModule_13_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_46 <= _oLSDAModule_14_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_47 <= _oLSDAModule_15_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_48 <= _oLSDAModule_16_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_49 <= _oLSDAModule_17_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_50 <= _oLSDAModule_18_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_51 <= _oLSDAModule_19_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_52 <= _oLSDAModule_20_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_53 <= _oLSDAModule_21_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_54 <= _oLSDAModule_22_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_55 <= _oLSDAModule_23_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_56 <= _oLSDAModule_24_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_57 <= _oLSDAModule_25_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_58 <= _oLSDAModule_26_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_59 <= _oLSDAModule_27_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_60 <= _oLSDAModule_28_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_61 <= _oLSDAModule_29_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
      regVecZ_62 <= _oLSDAModule_30_io_z;	// src/main/scala/neuron/components/online_adder.scala:77:29, src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24
    end
    else	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:30:14
      delayCount <= 6'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:53:27
  end // always @(posedge)
  ROO4_Verilog rOO4_VerilogModule (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_0),
    .io_xn (io_inputs_xn_1),
    .io_yp (io_inputs_yp_0),
    .io_yn (io_inputs_yn_1),
    .io_zp (_rOO4_VerilogModule_io_zp),
    .io_zn (_rOO4_VerilogModule_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_1 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_2),
    .io_xn (io_inputs_xn_3),
    .io_yp (io_inputs_yp_2),
    .io_yn (io_inputs_yn_3),
    .io_zp (_rOO4_VerilogModule_1_io_zp),
    .io_zn (_rOO4_VerilogModule_1_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_2 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_4),
    .io_xn (io_inputs_xn_5),
    .io_yp (io_inputs_yp_4),
    .io_yn (io_inputs_yn_5),
    .io_zp (_rOO4_VerilogModule_2_io_zp),
    .io_zn (_rOO4_VerilogModule_2_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_3 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_6),
    .io_xn (io_inputs_xn_7),
    .io_yp (io_inputs_yp_6),
    .io_yn (io_inputs_yn_7),
    .io_zp (_rOO4_VerilogModule_3_io_zp),
    .io_zn (_rOO4_VerilogModule_3_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_4 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_8),
    .io_xn (io_inputs_xn_9),
    .io_yp (io_inputs_yp_8),
    .io_yn (io_inputs_yn_9),
    .io_zp (_rOO4_VerilogModule_4_io_zp),
    .io_zn (_rOO4_VerilogModule_4_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_5 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_10),
    .io_xn (io_inputs_xn_11),
    .io_yp (io_inputs_yp_10),
    .io_yn (io_inputs_yn_11),
    .io_zp (_rOO4_VerilogModule_5_io_zp),
    .io_zn (_rOO4_VerilogModule_5_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_6 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_12),
    .io_xn (io_inputs_xn_13),
    .io_yp (io_inputs_yp_12),
    .io_yn (io_inputs_yn_13),
    .io_zp (_rOO4_VerilogModule_6_io_zp),
    .io_zn (_rOO4_VerilogModule_6_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_7 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_14),
    .io_xn (io_inputs_xn_15),
    .io_yp (io_inputs_yp_14),
    .io_yn (io_inputs_yn_15),
    .io_zp (_rOO4_VerilogModule_7_io_zp),
    .io_zn (_rOO4_VerilogModule_7_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_8 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_16),
    .io_xn (io_inputs_xn_17),
    .io_yp (io_inputs_yp_16),
    .io_yn (io_inputs_yn_17),
    .io_zp (_rOO4_VerilogModule_8_io_zp),
    .io_zn (_rOO4_VerilogModule_8_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_9 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_18),
    .io_xn (io_inputs_xn_19),
    .io_yp (io_inputs_yp_18),
    .io_yn (io_inputs_yn_19),
    .io_zp (_rOO4_VerilogModule_9_io_zp),
    .io_zn (_rOO4_VerilogModule_9_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_10 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_20),
    .io_xn (io_inputs_xn_21),
    .io_yp (io_inputs_yp_20),
    .io_yn (io_inputs_yn_21),
    .io_zp (_rOO4_VerilogModule_10_io_zp),
    .io_zn (_rOO4_VerilogModule_10_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_11 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_22),
    .io_xn (io_inputs_xn_23),
    .io_yp (io_inputs_yp_22),
    .io_yn (io_inputs_yn_23),
    .io_zp (_rOO4_VerilogModule_11_io_zp),
    .io_zn (_rOO4_VerilogModule_11_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_12 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_24),
    .io_xn (io_inputs_xn_25),
    .io_yp (io_inputs_yp_24),
    .io_yn (io_inputs_yn_25),
    .io_zp (_rOO4_VerilogModule_12_io_zp),
    .io_zn (_rOO4_VerilogModule_12_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_13 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_26),
    .io_xn (io_inputs_xn_27),
    .io_yp (io_inputs_yp_26),
    .io_yn (io_inputs_yn_27),
    .io_zp (_rOO4_VerilogModule_13_io_zp),
    .io_zn (_rOO4_VerilogModule_13_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_14 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_28),
    .io_xn (io_inputs_xn_29),
    .io_yp (io_inputs_yp_28),
    .io_yn (io_inputs_yn_29),
    .io_zp (_rOO4_VerilogModule_14_io_zp),
    .io_zn (_rOO4_VerilogModule_14_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_15 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_30),
    .io_xn (io_inputs_xn_31),
    .io_yp (io_inputs_yp_30),
    .io_yn (io_inputs_yn_31),
    .io_zp (_rOO4_VerilogModule_15_io_zp),
    .io_zn (_rOO4_VerilogModule_15_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_16 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_32),
    .io_xn (io_inputs_xn_33),
    .io_yp (io_inputs_yp_32),
    .io_yn (io_inputs_yn_33),
    .io_zp (_rOO4_VerilogModule_16_io_zp),
    .io_zn (_rOO4_VerilogModule_16_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_17 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_34),
    .io_xn (io_inputs_xn_35),
    .io_yp (io_inputs_yp_34),
    .io_yn (io_inputs_yn_35),
    .io_zp (_rOO4_VerilogModule_17_io_zp),
    .io_zn (_rOO4_VerilogModule_17_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_18 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_36),
    .io_xn (io_inputs_xn_37),
    .io_yp (io_inputs_yp_36),
    .io_yn (io_inputs_yn_37),
    .io_zp (_rOO4_VerilogModule_18_io_zp),
    .io_zn (_rOO4_VerilogModule_18_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_19 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_38),
    .io_xn (io_inputs_xn_39),
    .io_yp (io_inputs_yp_38),
    .io_yn (io_inputs_yn_39),
    .io_zp (_rOO4_VerilogModule_19_io_zp),
    .io_zn (_rOO4_VerilogModule_19_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_20 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_40),
    .io_xn (io_inputs_xn_41),
    .io_yp (io_inputs_yp_40),
    .io_yn (io_inputs_yn_41),
    .io_zp (_rOO4_VerilogModule_20_io_zp),
    .io_zn (_rOO4_VerilogModule_20_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_21 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_42),
    .io_xn (io_inputs_xn_43),
    .io_yp (io_inputs_yp_42),
    .io_yn (io_inputs_yn_43),
    .io_zp (_rOO4_VerilogModule_21_io_zp),
    .io_zn (_rOO4_VerilogModule_21_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_22 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_44),
    .io_xn (io_inputs_xn_45),
    .io_yp (io_inputs_yp_44),
    .io_yn (io_inputs_yn_45),
    .io_zp (_rOO4_VerilogModule_22_io_zp),
    .io_zn (_rOO4_VerilogModule_22_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_23 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_46),
    .io_xn (io_inputs_xn_47),
    .io_yp (io_inputs_yp_46),
    .io_yn (io_inputs_yn_47),
    .io_zp (_rOO4_VerilogModule_23_io_zp),
    .io_zn (_rOO4_VerilogModule_23_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_24 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_48),
    .io_xn (io_inputs_xn_49),
    .io_yp (io_inputs_yp_48),
    .io_yn (io_inputs_yn_49),
    .io_zp (_rOO4_VerilogModule_24_io_zp),
    .io_zn (_rOO4_VerilogModule_24_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_25 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_50),
    .io_xn (io_inputs_xn_51),
    .io_yp (io_inputs_yp_50),
    .io_yn (io_inputs_yn_51),
    .io_zp (_rOO4_VerilogModule_25_io_zp),
    .io_zn (_rOO4_VerilogModule_25_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_26 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_52),
    .io_xn (io_inputs_xn_53),
    .io_yp (io_inputs_yp_52),
    .io_yn (io_inputs_yn_53),
    .io_zp (_rOO4_VerilogModule_26_io_zp),
    .io_zn (_rOO4_VerilogModule_26_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_27 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_54),
    .io_xn (io_inputs_xn_55),
    .io_yp (io_inputs_yp_54),
    .io_yn (io_inputs_yn_55),
    .io_zp (_rOO4_VerilogModule_27_io_zp),
    .io_zn (_rOO4_VerilogModule_27_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_28 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_56),
    .io_xn (io_inputs_xn_57),
    .io_yp (io_inputs_yp_56),
    .io_yn (io_inputs_yn_57),
    .io_zp (_rOO4_VerilogModule_28_io_zp),
    .io_zn (_rOO4_VerilogModule_28_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_29 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_58),
    .io_xn (io_inputs_xn_59),
    .io_yp (io_inputs_yp_58),
    .io_yn (io_inputs_yn_59),
    .io_zp (_rOO4_VerilogModule_29_io_zp),
    .io_zn (_rOO4_VerilogModule_29_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_30 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_60),
    .io_xn (io_inputs_xn_61),
    .io_yp (io_inputs_yp_60),
    .io_yn (io_inputs_yn_61),
    .io_zp (_rOO4_VerilogModule_30_io_zp),
    .io_zn (_rOO4_VerilogModule_30_io_zn)
  );
  ROO4_Verilog rOO4_VerilogModule_31 (	// src/main/scala/neuron/components/online_multiplier.scala:100:36
    .clock (clock),
    .reset (reset),
    .io_xp (io_inputs_xp_62),
    .io_xn (io_inputs_xn_63),
    .io_yp (io_inputs_yp_62),
    .io_yn (io_inputs_yn_63),
    .io_zp (_rOO4_VerilogModule_31_io_zp),
    .io_zn (_rOO4_VerilogModule_31_io_zn)
  );
  OLSDA oLSDAModule (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_0, regVecZ_1}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_io_z)
  );
  OLSDA oLSDAModule_1 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_2, regVecZ_3}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_1_io_z)
  );
  OLSDA oLSDAModule_2 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_4, regVecZ_5}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_2_io_z)
  );
  OLSDA oLSDAModule_3 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_6, regVecZ_7}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_3_io_z)
  );
  OLSDA oLSDAModule_4 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_8, regVecZ_9}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_4_io_z)
  );
  OLSDA oLSDAModule_5 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_10, regVecZ_11}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_5_io_z)
  );
  OLSDA oLSDAModule_6 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_12, regVecZ_13}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_6_io_z)
  );
  OLSDA oLSDAModule_7 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_14, regVecZ_15}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_7_io_z)
  );
  OLSDA oLSDAModule_8 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_16, regVecZ_17}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_8_io_z)
  );
  OLSDA oLSDAModule_9 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_18, regVecZ_19}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_9_io_z)
  );
  OLSDA oLSDAModule_10 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_20, regVecZ_21}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_10_io_z)
  );
  OLSDA oLSDAModule_11 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_22, regVecZ_23}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_11_io_z)
  );
  OLSDA oLSDAModule_12 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_24, regVecZ_25}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_12_io_z)
  );
  OLSDA oLSDAModule_13 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_26, regVecZ_27}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_13_io_z)
  );
  OLSDA oLSDAModule_14 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_28, regVecZ_29}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_14_io_z)
  );
  OLSDA oLSDAModule_15 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_30, regVecZ_31}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_15_io_z)
  );
  OLSDA oLSDAModule_16 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_32, regVecZ_33}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_16_io_z)
  );
  OLSDA oLSDAModule_17 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_34, regVecZ_35}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_17_io_z)
  );
  OLSDA oLSDAModule_18 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_36, regVecZ_37}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_18_io_z)
  );
  OLSDA oLSDAModule_19 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_38, regVecZ_39}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_19_io_z)
  );
  OLSDA oLSDAModule_20 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_40, regVecZ_41}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_20_io_z)
  );
  OLSDA oLSDAModule_21 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_42, regVecZ_43}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_21_io_z)
  );
  OLSDA oLSDAModule_22 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_44, regVecZ_45}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_22_io_z)
  );
  OLSDA oLSDAModule_23 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_46, regVecZ_47}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_23_io_z)
  );
  OLSDA oLSDAModule_24 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_48, regVecZ_49}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_24_io_z)
  );
  OLSDA oLSDAModule_25 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_50, regVecZ_51}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_25_io_z)
  );
  OLSDA oLSDAModule_26 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_52, regVecZ_53}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_26_io_z)
  );
  OLSDA oLSDAModule_27 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_54, regVecZ_55}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_27_io_z)
  );
  OLSDA oLSDAModule_28 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_56, regVecZ_57}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_28_io_z)
  );
  OLSDA oLSDAModule_29 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_58, regVecZ_59}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_29_io_z)
  );
  OLSDA oLSDAModule_30 (	// src/main/scala/neuron/components/online_adder.scala:77:29
    .clock (clock),
    .reset (reset),
    .io_x  ({regVecZ_60, regVecZ_61}),	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:56:24, :140:16
    .io_z  (_oLSDAModule_30_io_z)
  );
  assign io_result = io_start ? regVecZ_62 : 2'h0;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7, :56:24, :57:12, :69:15, :76:18, :165:17
  assign io_resultValid = io_start & _GEN;	// src/main/scala/neuron/components/online_multiple_multiplication_addition.scala:16:7, :76:18, :81:{21,44}, :166:17
endmodule

